// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsc1hnav-TZCJMyyT3MaIARzScLXhF7zQ',
    appId: '1:893336919605:web:aa777955913a0d97b19b7c',
    messagingSenderId: '893336919605',
    projectId: 'dino-run-flutter',
    authDomain: 'dino-run-flutter.firebaseapp.com',
    databaseURL: 'https://dino-run-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'dino-run-flutter.appspot.com',
    measurementId: 'G-DJPFQ2N119',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeCt_QsSlDBBDOOXb9foNaW1E5aeWzgCo',
    appId: '1:893336919605:android:7d9e186a4f29152eb19b7c',
    messagingSenderId: '893336919605',
    projectId: 'dino-run-flutter',
    databaseURL: 'https://dino-run-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'dino-run-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyQ63mTlqRt2qagq3gbuE3NSwKHtQVQXk',
    appId: '1:893336919605:ios:e2fbe0fdf4bedb4eb19b7c',
    messagingSenderId: '893336919605',
    projectId: 'dino-run-flutter',
    databaseURL: 'https://dino-run-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'dino-run-flutter.appspot.com',
    iosClientId: '893336919605-5krr4bj6iefk98l4o8h1rbde5aj154o6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterGameFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyQ63mTlqRt2qagq3gbuE3NSwKHtQVQXk',
    appId: '1:893336919605:ios:e2fbe0fdf4bedb4eb19b7c',
    messagingSenderId: '893336919605',
    projectId: 'dino-run-flutter',
    databaseURL: 'https://dino-run-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'dino-run-flutter.appspot.com',
    iosClientId: '893336919605-5krr4bj6iefk98l4o8h1rbde5aj154o6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterGameFirebase',
  );
}
